spring:
  config:
    activate:
      on-profile: default

---

server:
  port: 80
  compression.enabled: true

#server.servlet.context-path: /casino
spring:
  webflux:
    base-path: /casino

---

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management.endpoints.web.exposure.include: info,health,metrics,refresh

springdoc:
  swagger-ui:
    enabled: true

---

spring:
  r2dbc:
    url: r2dbc:h2:file:///./.casino

---

spring:
  liquibase:
    url: jdbc:h2:file:./.casino
    enabled: true
    change-log : db/changelog/changelog-master.xml
